var f=void 0,g=!0,i=null,k=!1;function l(){return function(){}}var m,n=this;
function aa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function ba(a){var b=aa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function o(a){return"string"==typeof a}function ca(a,b,c){return a.call.apply(a.bind,arguments)}
function da(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function p(a,b,c){p=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ca:da;return p.apply(i,arguments)}
function q(a,b){var c=a.split("."),d=n;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&b!==f?d[e]=b:d=d[e]?d[e]:d[e]={}}function t(a,b){function c(){}c.prototype=b.prototype;a.Da=b.prototype;a.prototype=new c;a.prototype.constructor=a};var ea=/^\s*$/;function fa(a,b){return o(a)?b==a:!(!b||!b.match(a))}function ga(a,b){return fa(a,b in this?this[b]:this.getAttribute?this.getAttribute(b):i)};function u(){}u.prototype.k=i;u.prototype.reset=l();u.prototype.a=function(){return 0};function w(){}t(w,u);w.prototype.e=0;w.prototype.a=function(a,b){this.e+=b;if(0<=this.e)return 1;this.e=0;return 3};w.prototype.reset=function(){this.e=0};function ha(a,b){for(var c in a)if(!ga.call(b,a[c],c))return k;return g};function x(a,b,c,d,e){this.va=o(a)?a.toUpperCase():a;this.xa=b;this.H=c||i;this.P=d||i;this.S=e||i}t(x,u);x.prototype.H=i;x.prototype.P=i;x.prototype.S=i;x.prototype.a=function(a,b){if(b==this.xa&&fa(this.va,a.nodeName)){if(this.H&&!ha(this.H,a)||this.P&&!ha(this.P,a.style)||this.S&&!this.S(a))return 0;this.k=a;return 2}return 0};function ia(a){for(var b=0,c=(""+ja).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),a=(""+a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=Math.max(c.length,a.length),e=0;0==b&&e<d;e++){var j=c[e]||"",h=a[e]||"",r=RegExp("(\\d*)(\\D*)","g"),s=RegExp("(\\d*)(\\D*)","g");do{var B=r.exec(j)||["","",""],E=s.exec(h)||["","",""];if(0==B[0].length&&0==E[0].length)break;b=((0==B[1].length?0:parseInt(B[1],10))<(0==E[1].length?0:parseInt(E[1],10))?-1:(0==B[1].length?0:parseInt(B[1],10))>(0==E[1].length?
0:parseInt(E[1],10))?1:0)||((0==B[2].length)<(0==E[2].length)?-1:(0==B[2].length)>(0==E[2].length)?1:0)||(B[2]<E[2]?-1:B[2]>E[2]?1:0)}while(0==b)}return b};var y,ka,A,la;function ma(){return n.navigator?n.navigator.userAgent:i}la=A=ka=y=k;var C;if(C=ma()){var na=n.navigator;y=0==C.indexOf("Opera");ka=!y&&-1!=C.indexOf("MSIE");A=!y&&-1!=C.indexOf("WebKit");la=!y&&!A&&"Gecko"==na.product}var D=ka,oa=la,pa=A,ja;
a:{var qa="",F;if(y&&n.opera)var ra=n.opera.version,qa="function"==typeof ra?ra():ra;else if(oa?F=/rv\:([^\);]+)(\)|;)/:D?F=/MSIE\s+([^\);]+)(\)|;)/:pa&&(F=/WebKit\/(\S+)/),F)var sa=F.exec(ma()),qa=sa?sa[1]:"";if(D){var ta,ua=n.document;ta=ua?ua.documentMode:f;if(ta>parseFloat(qa)){ja=""+ta;break a}}ja=qa}var va={},wa={};function xa(){return wa[9]||(wa[9]=D&&!!document.documentMode&&9<=document.documentMode)};!D||xa();if(oa||D)if(!D||!xa())oa&&(va["1.9.1"]||(va["1.9.1"]=0<=ia("1.9.1")));D&&(va["9"]||(va["9"]=0<=ia("9")));function G(a){return o(a)?document.getElementById(a):a};function H(a,b,c,d){x.call(this,a,1,b,c,d)}t(H,x);function ya(a,b,c,d){x.call(this,a,1,b,c,d)}t(ya,H);ya.prototype.e=0;ya.prototype.a=function(a,b){if(this.e)return(this.e+=b)?1:2;return x.prototype.a.call(this,a,b)?(this.e=b,1):0};var J;function K(a,b,c,d,e){this.I=a;this.g=b;this.G=c;this.la=d;this.p=e}K.prototype.getName=function(){return this.g};
function za(a){var b=[a.I?M(a.I)+".":"",a.g?M(J?J(a.g):a.g):"anonymous",M(a.la),a.G?" [as "+M(J?J(a.G):a.G)+"]":""];if(a.p)if(b.push(" at "),Boolean(n.CLOSURE_INSPECTOR___&&n.CLOSURE_INSPECTOR___.supportsJSUnit)){var c=a.p.match(/\d+$/)[0];b.push('<a href="" onclick="CLOSURE_INSPECTOR___.showLine(\'',M(a.p),"', '",c,"'); return false\">",M(a.p),"</a>")}else b.push(M(a.p));return b.join("")}
var Aa=RegExp("^    at(?: (?:(.*?)\\.)?((?:new )?(?:[a-zA-Z_$][\\w$]*|<anonymous>))(?: \\[as ([a-zA-Z_$][\\w$]*)\\])?)? (?:\\(unknown source\\)|\\(native\\)|\\((?:eval at )?((?:http|https|file)://[^\\s)]+|javascript:.*)\\)|((?:http|https|file)://[^\\s)]+|javascript:.*))$"),Ba=/^([a-zA-Z_$][\w$]*)?(\(.*\))?@(?::0|((?:http|https|file):\/\/[^\s)]+|javascript:.*))$/,Ca=/^function ([a-zA-Z_$][\w$]*)/;
function Da(){for(var a=[],b=arguments.callee.caller,c=0;b&&20>c;){var d=Function.prototype.toString.call(b).match(Ca),d=d?d[1]:"",e=["("];if(b.arguments)for(var j=0;j<b.arguments.length;j++){var h=b.arguments[j];0<j&&e.push(", ");o(h)?e.push('"',h,'"'):h&&h.$replay?e.push("goog.testing.Mock"):e.push(""+h)}else e.push("unknown");e.push(")");a.push(new K("",d,"",e.join(""),""));try{b=b.caller}catch(r){break}c++}return a}
function Ea(a){var b=a.match(Aa);if(b)return new K(b[1]||"",b[2]||"",b[3]||"","",b[4]||b[5]||"");if(5E5<a.length){var b=a.indexOf("("),c=a.lastIndexOf("@"),d=a.lastIndexOf(":"),e="";0<=b&&b<c&&(e=a.substring(0,b));var j="";0<=c&&c+1<d&&(j=a.substring(c+1));d="";0<=b&&0<c&&b<c&&(d=a.substring(b,c));return new K("",e,"",d,j)}return(b=a.match(Ba))?new K("",b[1]||"","",b[2]||"",b[3]||""):i}function M(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function Fa(a){for(var b=a.length-1;a[b]&&(!a[b].g||"[object Object]"==a[b].I);)b--;for(var c=-1,d=0;d<a.length;d++)if(a[d]&&"_assert"==a[d].getName()){c=d;break}for(var e=[],d=c+1;d<=b;d++)e.push("> "),a[d]?e.push(za(a[d])):e.push("(unknown)"),e.push("\n");return e.join("")}function Ga(a){for(var a=a.replace(/\s*$/,"").split("\n"),b=[],c=0;c<a.length;c++)b.push(Ea(a[c]));return b}q("setDeobfuscateFunctionName",function(a){J=a});function Ha(a,b){return a==b}function Ia(a,b){return a.toString()===b.toString()}var Ja={String:Ha,Number:Ha,Boolean:Ha,Date:function(a,b){return a.getTime()==b.getTime()},RegExp:Ia,Function:Ia};function Ka(a,b,c){return Math.abs(a-b)<=c}var La={Number:Ka};
function N(a){var b=typeof a;try{switch(b){case "object":if(a==i){b="null";break}case "function":switch(a.constructor){case (new String("")).constructor:b="String";break;case (new Boolean(g)).constructor:b="Boolean";break;case (new Number(0)).constructor:b="Number";break;case [].constructor:b="Array";break;case RegExp().constructor:b="RegExp";break;case (new Date).constructor:b="Date";break;case Function:b="Function";break;default:var c=a.constructor.toString().match(/function\s*([^( ]+)\(/);c&&(b=
c[1])}break}}catch(d){}finally{b=b.substr(0,1).toUpperCase()+b.substr(1)}return b}function O(a){var b="<"+a+">";a===i||a===f||(b+=" ("+N(a)+")");return b}function P(a,b){return b.length==a+1?b[0]:i}function Q(a,b,c){return c.length==b+1?c[a]:c[a-1]}function R(a,b){b.length==a||b.length==a+1&&o(b[0])||S(i,"Incorrect arguments passed to assert function")}
function Ma(a,b){R(1,arguments);var c=P(1,arguments),d=Q(1,1,arguments);"boolean"==typeof d||S(c,"Bad argument to assert(boolean)");d||S(c,"Call to assert(boolean) with false")}function Na(a,b){R(1,arguments);var c=P(1,arguments),d=Q(1,1,arguments);"boolean"==typeof d||S(c,"Bad argument to assertTrue(boolean)");d||S(c,"Call to assertTrue(boolean) with false")}function T(a,b,c){R(2,arguments);var d=Q(1,2,arguments),e=Q(2,2,arguments),j="Expected "+O(d)+" but was "+O(e);d===e||S(P(2,arguments),j)}
function Oa(a,b){R(1,arguments);var c="Expected not to be "+O(i);Q(1,1,arguments)!==i||S(P(1,arguments),c)}function Pa(a,b){R(1,arguments);var c="Expected not to be "+O(f);Q(1,1,arguments)!==f||S(P(1,arguments),c)}var Qa=i,Ra="";
function Sa(a,b,c){function d(a,b,c){var z=j.length;if(z%2){var I=z>>1,z=j[I]===a,I=h[I]===b;if(z||I){(!z||!I)&&e.push("Asymmetric cycle detected at "+c);return}}j.push(a);h.push(b);if(a!==b)if(z=N(a),I=N(b),z==I){var W="Array"==z,L=r(z,a,b);if(L!=Qa)L!=Ra&&e.push(c+" "+L);else if(W&&a.length!=b.length)e.push(c+" expected "+a.length+"-element array but got a "+b.length+"-element array");else if(L=c+(W?"[%s]":c?".%s":"%s"),a.__iterator__)"function"==aa(a.na)?a.na(b)||e.push("equals() returned false for "+
(c||z)):a.Z?d(a.Z,b.Z,L.replace("%s","map_")):e.push("unable to check "+(c||z)+" for equality: it has an iterator we do not know how to handle. please add an equals method");else{for(var v in a)if(!W||(v|0)!=v)v in b?d(a[v],b[v],L.replace("%s",v)):e.push("property "+v+" not present in actual "+(c||I));for(v in b)if(!W||(v|0)!=v)v in a||e.push("property "+v+" not present in expected "+(c||z));if(W)for(v=0;v<a.length;v++)d(a[v],b[v],L.replace("%s",""+v))}}else e.push(c+" expected "+O(a)+" but was "+
O(b));j.pop();h.pop()}var e=[],j=[],h=[],r=c||function(a,b,c){a=Ja[a];return!a?Qa:a(b,c)?Ra:"expected "+O(b)+" but was "+O(c)};d(a,b,"");return 0==e.length?i:"Expected "+O(a)+" but was "+O(b)+"\n   "+e.join("\n   ")}function Ta(a,b,c){R(2,arguments);var d=P(2,arguments)?P(2,arguments):"",e=Sa(Q(1,2,arguments),Q(2,2,arguments));!e||S(d,e)}
function Ua(a,b,c,d){R(3,arguments);var e=Q(1,3,arguments),j=Q(2,3,arguments),h=Q(3,3,arguments);Ka(e,j,h)||S(P(3,arguments),"Expected "+e+", but got "+j+" which was more than "+h+" away")}function Va(a){for(var b=[],c=0;c<a.length;c++)b[c]=a[c];return b}function Wa(a,b){if(a.indexOf)return a.indexOf(b);for(var c=0;c<a.length;c++)if(a[c]===b)return c;return-1}function Xa(a){var b=document.createElement("DIV");b.innerHTML=a;return b.innerHTML.replace(/^\s+|\s+$/g,"")}
function S(a,b){n.CLOSURE_INSPECTOR___&&n.CLOSURE_INSPECTOR___.supportsJSUnit&&n.CLOSURE_INSPECTOR___.jsUnitFailure(a,b);throw new Ya(a,b);}function Ya(a,b){this.za=g;this.message=(a?a:"")+(a&&b?"\n":"")+(b?b:"");var c=Error().stack,c=c?Ga(c):Da();this.Ca=Fa(c);this.ya=a||i;this.Aa=b||""}Ya.prototype.toString=function(){return"[JsUnitException]"};q("fail",function(a){S("Call to fail()",a)});q("assert",Ma);
q("assertThrows",function(a,b){R(1,arguments);var c=Q(1,1,arguments),d=P(1,arguments);"function"==typeof c||S(d,"Argument passed to assertThrows is not a function");try{c()}catch(e){if(e&&o(e.stacktrace)&&o(e.message))c=e.message.length-e.stacktrace.length,e.message.indexOf(e.stacktrace,c)==c&&(e.message=e.message.substr(0,c-14));return e}S(d,"No exception thrown from function passed to assertThrows")});
q("assertNotThrows",function(a,b){R(1,arguments);var c=P(1,arguments),d=Q(1,1,arguments);"function"==typeof d||S(c,"Argument passed to assertNotThrows is not a function");try{d()}catch(e){S((c?c+"\n":"")+"A non expected exception was thrown from function passed to assertNotThrows",e.stack||e.stacktrace||e.toString())}});q("assertTrue",Na);q("assertFalse",function(a,b){R(1,arguments);var c=P(1,arguments),d=Q(1,1,arguments);"boolean"==typeof d||S(c,"Bad argument to assertFalse(boolean)");!d||S(c,"Call to assertFalse(boolean) with true")});
q("assertEquals",T);q("assertNotEquals",function(a,b,c){R(2,arguments);var d=Q(2,2,arguments),e="Expected not to be "+O(d);Q(1,2,arguments)!==d||S(P(2,arguments),e)});q("assertNull",function(a,b){R(1,arguments);var c=Q(1,1,arguments),d="Expected "+O(i)+" but was "+O(c);c===i||S(P(1,arguments),d)});q("assertNotNull",Oa);q("assertUndefined",function(a,b){R(1,arguments);var c=Q(1,1,arguments),d="Expected "+O(f)+" but was "+O(c);c===f||S(P(1,arguments),d)});q("assertNotUndefined",Pa);
q("assertNotNullNorUndefined",function(a,b){R(1,arguments);Oa.apply(i,arguments);Pa.apply(i,arguments)});q("assertNonEmptyString",function(a,b){R(1,arguments);var c=Q(1,1,arguments),d="Expected non-empty string but was "+O(c);c!==f&&c!==i&&"string"==typeof c&&""!==c||S(P(1,arguments),d)});q("assertNaN",function(a,b){R(1,arguments);isNaN(Q(1,1,arguments))||S(P(1,arguments),"Expected NaN")});q("assertNotNaN",function(a,b){R(1,arguments);!isNaN(Q(1,1,arguments))||S(P(1,arguments),"Expected not NaN")});
q("assertObjectEquals",Ta);q("assertObjectRoughlyEquals",function(a,b,c,d){R(3,arguments);var e=Q(3,3,arguments),j=P(3,arguments)?P(3,arguments):"",h=Sa(Q(1,3,arguments),Q(2,3,arguments),function(a,b,c){a=La[a];return!a?Qa:a(b,c,e)?Ra:"expected "+O(b)+" but was "+O(c)+" which was more than "+e+" away"});!h||S(j,h)});q("assertObjectNotEquals",function(a,b,c){R(2,arguments);var d=P(2,arguments)?P(2,arguments):"";Sa(Q(1,2,arguments),Q(2,2,arguments))||S(d,"Objects should not be equal")});
q("assertArrayEquals",function(a,b,c){R(2,arguments);var d=Q(1,2,arguments),e=Q(2,2,arguments),j=P(2,arguments)?P(2,arguments):"",h=N(d);"Array"==h||S(j,"Expected an array for assertArrayEquals but found a "+h);h=N(e);"Array"==h||S(j,"Expected an array for assertArrayEquals but found a "+h);Ta(j,Array.prototype.concat.call(d),Array.prototype.concat.call(e))});
q("assertElementsEquals",function(a,b,c){R(2,arguments);var d=Q(1,2,arguments),e=Q(2,2,arguments),j=P(2,arguments)?P(2,arguments):"";if(d){T("length mismatch: "+j,d.length,e.length);for(var h=0;h<d.length;++h)T("mismatch at index "+h+": "+j,d[h],e[h])}else Ma(j,!e)});
q("assertElementsRoughlyEqual",function(a,b,c,d){R(3,arguments);var e=Q(1,3,arguments),j=Q(2,3,arguments),h=Q(3,3,arguments),r=P(3,arguments)?P(3,arguments):"";if(e){T("length mismatch: "+r,e.length,j.length);for(var s=0;s<e.length;++s)Ua(r,e[s],j[s],h)}else Ma(r,!j)});
q("assertSameElements",function(a,b,c){R(2,arguments);var d=Q(1,2,arguments),e=Q(2,2,arguments),j=P(2,arguments);Na("Bad arguments to assertSameElements(opt_message, expected: ArrayLike, actual: ArrayLike)",ba(d)&&ba(e));d=Va(d);e=Va(e);d.length==e.length||S(j,"Expected "+d.length+" elements: ["+d+"], got "+e.length+" elements: ["+e+"]");for(var h=Va(d),r=0;r<e.length;r++){var s=Wa(h,e[r]);-1!=s||S(j,"Expected ["+d+"], got ["+e+"]");h.splice(s,1)}});
q("assertEvaluatesToTrue",function(a,b){R(1,arguments);Q(1,1,arguments)||S(P(1,arguments),"Expected to evaluate to true")});q("assertEvaluatesToFalse",function(a,b){R(1,arguments);Q(1,1,arguments)&&S(P(1,arguments),"Expected to evaluate to false")});q("assertHTMLEquals",function(a,b,c){R(2,arguments);var d=Q(2,2,arguments),e=Xa(Q(1,2,arguments)),d=Xa(d),j="Expected "+O(e)+" but was "+O(d);e===d||S(P(2,arguments),j)});
q("assertHashEquals",function(a,b,c){R(2,arguments);var d=Q(1,2,arguments),e=Q(2,2,arguments),j=P(2,arguments),h;for(h in d)h in e||S(j,"Expected hash had key "+h+" that was not found"),d[h]==e[h]||S(j,"Value for key "+h+" mismatch - expected = "+d[h]+", actual = "+e[h]);for(h in e)h in d||S(j,"Actual hash had key "+h+" that was not expected")});q("assertRoughlyEquals",Ua);
q("assertContains",function(a,b,c){R(2,arguments);var d=Q(1,2,arguments),e=Q(2,2,arguments);-1!=Wa(e,d)||S(P(2,arguments),"Expected '"+e+"' to contain '"+d+"'")});q("assertNotContains",function(a,b,c){R(2,arguments);var d=Q(1,2,arguments),e=Q(2,2,arguments);-1==Wa(e,d)||S(P(2,arguments),"Expected '"+e+"' not to contain '"+d+"'")});function Za(a){this.g=a||"Untitled Test Case";this.u=[];this.t=i;var a=window.location.search,b=a.match(/(?:\?|&)runTests=([^?&]+)/i);if(b){this.t={};for(var b=b[1].split(","),c=0,d=b.length;c<d;c++)this.t[b[c]]=1}if(a=a.match(/(?:\?|&)order=(natural|random|sorted)/i))this.ca=a[1];this.c=new $a(this)}Za.prototype.ca="sorted";var ab=window.setTimeout,bb=""+window.setTimeout,cb=i,db="undefined"==typeof opera&&!!navigator&&-1!=navigator.userAgent.indexOf("MSIE");m=Za.prototype;m.ia=k;m.r=k;m.ha=0;
m.U=0;m.v=0;m.C=i;m.s=i;m.add=function(a){this.u.push(a)};m.next=function(){for(var a;a=this.u[this.v++];)if(!this.t||this.t[a.name]||this.t[this.v-1])return a;return i};m.reset=function(){this.v=0;this.c=new $a(this)};m.ga=function(){return g};m.execute=function(){this.ia=g;this.reset();this.ha=this.now();this.r=g;this.c.T=this.u.length;this.ga()?(this.log("Starting tests: "+this.g),this.V()):(this.log("shouldRunTests() returned false, skipping these tests."),this.c.R=g,eb(this))};
function eb(a){U(a,"Done");a.ka();var b=ab==window.setTimeout;!b&&db&&""+window.setTimeout==bb&&(b=g);b||(U(a,"ERROR: Test did not restore setTimeout"),a.c.d.push(new fb(a.g,"ERROR: Test did not restore setTimeout")));window.setTimeout=ab;a.ma=a.now();a.r=k;a.c.D=a.ma-a.ha;for(var b=document.getElementsByTagName("script"),c=0,d=0,e=b.length;d<e;d++)b[d].src&&c++;a.c.N=c;a.log(gb(a.c));a.c.j()?a.log("Tests complete"):a.log("Tests Failed");if(a.C)b=a.C,b(),a.C=i}
function U(a,b){a.c.$.push(hb()+"  "+b)}m.log=function(a){var b=n.top;!(b&&"undefined"!=typeof b._allTests)&&window.console&&("string"==typeof a&&(a=hb()+" : "+a),a instanceof Error&&a.stack?window.console.log(a,a.message,a.stack):window.console.log(a))};m.j=function(){return!!this.c&&this.c.j()};
m.w=function(a){var b=[];if(this.s&&!this.s.Y())b.push(this.g+" [RUNNING]");else{var c=this.c.j()&&!(0<this.s.d.length);b.push(this.g+" ["+(c?"PASSED":"FAILED")+"]")}c=window.location.href;b.push(c.substring(c.indexOf("google3")+8));b.push(gb(this.c));a?b.push(".",this.c.$.join("\n")):this.c.j()||b.push(this.c.d.join("\n"));b.push(" ");return b.join("\n")};m.L=function(){return this.c.D};m.K=function(){return this.c.N};m.da=function(){this.fa();this.execute()};
function ib(a,b){switch(a.ca){case "random":for(var c=b.length;1<c;){var d=Math.floor(Math.random()*c);c--;var e=b[c];b[c]=b[d];b[d]=e}break;case "sorted":b.sort(function(a,b){return a.name==b.name?0:a.name<b.name?-1:1})}}m.fa=l();m.ka=l();m.ea=l();m.Q=l();
m.V=function(){U(this,"Start");this.U=this.now();for(var a;(a=this.next())&&this.r;){this.c.n++;var b=k;try{this.log("Running test: "+a.name);cb=a.name;this.ea();a.execute();this.Q();cb=i;var b=g,c=a;this.c.F++;var d=c.name+" : PASSED";U(this,d);this.log(d)}catch(e){var c=e,j=a.name+" : FAILED";this.log(j);U(this,j);this.c.d.push(this.m(a.name,c));if(!b)try{this.Q()}catch(h){}}if(this.v<this.u.length&&200<this.now()-this.U){U(this,"Breaking async");this.timeout(p(this.V,this),100);return}}eb(this)};
m.timeout=function(a,b){return ab(a,b)};m.now=function(){return(new Date).getTime()};function hb(){var a=new Date,b="00"+a.getMilliseconds(),b=b.substr(b.length-3);return(10>a.getHours()?"0"+a.getHours():""+a.getHours())+":"+(10>a.getMinutes()?"0"+a.getMinutes():""+a.getMinutes())+":"+(10>a.getSeconds()?"0"+a.getSeconds():""+a.getSeconds())+"."+b}
m.m=function(a,b){var c=i,d=i;b?(this.log(b),o(b)?c=b:(c=b.message||b.description||b.toString(),b.stack?(d=Ga(b.stack),d=Fa(d)):d=b.stackTrace)):c="An unknown error occurred";c=new fb(a,c,d);(!b||!b.isJsUnitException||!b.loggedJsUnitException)&&U(this,c.toString());b&&b.isJsUnitException&&(b.loggedJsUnitException=g);return c};function jb(a,b,c){this.name=a;this.ta=b;this.scope=c||i}jb.prototype.execute=function(){this.ta.call(this.scope)};
function $a(a){this.wa=a;this.N=this.D=this.F=this.n=this.T=0;this.R=k;this.d=[];this.$=[]}$a.prototype.j=function(){var a=this.n==this.F&&0==this.d.length;return a&&!this.R&&this.A()?0<this.n:a};
function gb(a){var b=a.n+" of "+a.T+" tests run in "+a.D+"ms.\n";a.R?b+="Tests not run because shouldRunTests() returned false.":0==a.n?(b+="No tests found.  ",a.A()&&(b+="Call G_testRunner.setStrict(false) if this is expected behavior.  ")):b+=a.F+" passed, "+(a.T-a.F)+" failed.\n"+Math.round(a.D/a.n)+" ms/test. "+a.N+" files loaded.";return b}$a.prototype.A=function(){return this.wa.s.A()};function fb(a,b,c){this.source=a;this.message=b;this.stack=c||i}
fb.prototype.toString=function(){return"ERROR in "+this.source+"\n"+this.message+(this.stack?"\n"+this.stack:"")};function kb(){this.d=[]}m=kb.prototype;m.b=i;m.z=k;m.B=i;m.J=i;m.ja=g;m.X=function(a){if(!this.B){var b=document.getElementById("closureTestRunnerLog");b==i&&(b=document.createElement("div"),document.body.appendChild(b));this.B=b}if(this.b&&this.b.r)throw Error("The test runner is already waiting for a test to complete");this.b=a;a.s=this;this.z=g};m.ua=function(a){this.ja=a};m.A=function(){return this.ja};m.oa=function(){return this.z};
m.Y=function(){return 0<this.d.length||this.z&&!!this.b&&this.b.ia&&!this.b.r};m.j=function(){return!(0<this.d.length)&&!!this.b&&this.b.j()};m.m=function(a){(!this.J||this.J.call(i,a))&&this.d.push(a)};m.pa=function(a){var b=cb;if(this.b)this.b.m(b,a);else throw Error("Test runner not initialized with a test case. Original exception: "+a.message);};
m.w=function(a){var b=[];this.b&&b.push(this.b.w(a));0<this.d.length&&(b.push("JavaScript errors detected by test runner:"),b.push.apply(b,this.d),b.push("\n"));return b.join("\n")};m.L=function(){return this.b?this.b.L():0};m.K=function(){return this.b?this.b.K():0};m.execute=function(){if(!this.b)throw Error("The test runner must be initialized with a test case before execute can be called.");this.b.C=p(this.sa,this);this.b.da()};
m.sa=function(){var a=this.b.w(g);0<this.d.length&&(a+="\n"+this.d.join("\n"));for(var b=this.B;b.firstChild;)b.removeChild(b.firstChild);lb(this,a);a=document.createElement("a");a.style.display="block";a.style.fontSize="small";a.href="";a.onclick=p(function(){this.execute();return k},this);a.innerHTML="Run again without reloading";b.appendChild(a)};
function lb(a,b){for(var c=b.split("\n"),d=0;d<c.length;d++){var e=c[d],j,h=/FAILED/.test(e)||/ERROR/.test(e);j=/PASSED/.test(e)?"darkgreen":h?"darkred":"#333";var r=document.createElement("div");"> "==e.substr(0,2)?r.innerHTML=e:r.appendChild(document.createTextNode(e));if(h&&(e=/(\S+) (\[[^\]]*] )?: (FAILED|ERROR)/.exec(e))){e="runTests="+e[1];if(h=window.location.search)var s=/runTests=([^&]*)/.exec(h),e=s?h.substr(0,s.index)+e+h.substr(s.index+s[0].length):h+"&"+e;else e="?"+e;h=window.location.href;
(s=window.location.hash)&&"#"!=s.charAt(0)&&(s="#"+s);h=h.split("#")[0].split("?")[0]+e+s;e=document.createElement("A");e.innerHTML="(run individually)";e.style.fontSize="0.8em";e.href=h;r.appendChild(document.createTextNode(" "));r.appendChild(e)}r.style.color=j;r.style.font="normal 100% monospace";try{r.style.whiteSpace="pre-wrap"}catch(B){}if(2>d)r.style.fontWeight="bold";a.B.appendChild(r)}}m.log=function(a){this.b&&this.b.log(a)};(function(){Error.stackTraceLimit=50;var a=window.setTimeout;if(top.JsUnitTestManager||top.jsUnitTestManager)document.write('<script type="text/javascript" src="../../third_party/java/jsunit/core/app/jsUnitCore.js"><\/script>');else{var b=new kb;q("G_testRunner",b);q("G_testRunner.initialize",b.X);q("G_testRunner.isInitialized",b.oa);q("G_testRunner.isFinished",b.Y);q("G_testRunner.isSuccess",b.j);q("G_testRunner.getReport",b.w);q("G_testRunner.getRunTime",b.L);q("G_testRunner.getNumFilesLoaded",
b.K);q("G_testRunner.setStrict",b.ua);q("G_testRunner.logTestFailure",b.pa);n.debug||q("debug",p(b.log,b));if(n.G_errorFilter)b.J=n.G_errorFilter;var c=window.onerror;window.onerror=function(a,d,h){c&&c(a,d,h);"object"==typeof a?a.target&&"SCRIPT"==a.target.tagName?b.m("UNKNOWN ERROR: Script "+a.target.src):b.m("UNKNOWN ERROR: No error information available."):b.m("JS ERROR: "+a+"\nURL: "+d+"\nLine: "+h)};var d=window.onload;window.onload=function(){d&&d();a(function(){if(!b.z){var a=new Za(document.title),
c="undefined"!=typeof n.RuntimeObject?n.RuntimeObject("test*"):n,d=[],r;for(r in c){try{var s=c[r]}catch(B){}/^test/.test(r)&&"function"==aa(s)&&d.push(new jb(r,s,n))}ib(a,d);for(c=0;c<d.length;c++)a.add(d[c]);a.log(a.u.length+" tests auto-discovered");if(n.setUp)a.ea=p(n.setUp,n);if(n.tearDown)a.Q=p(n.tearDown,n);if(n.setUpPage)a.fa=p(n.setUpPage,n);if(n.tearDownPage)a.ka=p(n.tearDownPage,n);if(n.runTests)a.da=p(n.runTests,n);if(n.shouldRunTests)a.ga=p(n.shouldRunTests,n);b.X(a)}b.execute()},500);
window.onload=i}}})();function V(a,b,c,d){x.call(this,a,-1,b,c,d)}t(V,x);function X(a){this.qa=a}t(X,u);X.prototype.a=function(a){return 3==a.nodeType&&fa(this.qa,a.nodeValue)?(this.k=a,2):0};function Y(a,b){this.o=a;this.l=[];this.aa=b||0}t(Y,w);Y.prototype.aa=0;Y.prototype.h=k;Y.prototype.a=function(a,b){this.h&&this.reset();var c=w.prototype.a.apply(this,arguments);switch(c){case 1:c=k;switch(this.o.a(a,b)){case 3:c=g;case 2:this.l.push(this.o.k)}c&&2==this.o.a(a,b)&&this.l.push(this.o.k);return 1;case 3:return this.h=g,this.l.length>=this.aa?3:0;default:return this.h=g,c}};Y.prototype.reset=function(){this.h=k;this.l.length=0;this.o.reset();w.prototype.reset.call(this)};function Z(a,b,c){this.O=a;this.ba=b||0;this.M=c||i;this.l=[]}t(Z,u);m=Z.prototype;m.ba=0;m.M=0;m.i=0;m.h=k;m.a=function(a,b){this.h&&this.reset();if(3==a.nodeType&&a.nodeValue.match(/^\s+$/))return 1;switch(this.O.a(a,b)){case 2:if(0==this.i)this.k=a;this.i++;this.l.push(this.O.k);return this.M!==i&&this.i==this.M?(this.h=g,2):1;case 1:return 1;case 3:this.i++;return this.f==this.Ba.length?(this.h=g,3):this.a(a,b);default:return this.h=g,this.i>=this.ba?3:0}};
m.reset=function(){this.O.reset();this.i=0;this.h=k;this.l.length=0};function mb(a){this.ra=a}t(mb,u);mb.prototype.a=function(a){return a.nodeType==this.ra?2:0};function $(a,b){this.q=a;this.W=!!b}t($,u);$.prototype.f=0;$.prototype.W=k;$.prototype.a=function(a,b){if(this.W&&3==a.nodeType&&ea.test(a.nodeValue))return 1;switch(this.q[this.f].a(a,b)){case 2:if(0==this.f)this.k=a;this.f++;return this.f==this.q.length?(this.reset(),2):1;case 1:return 1;case 3:this.f++;return this.f==this.q.length?(this.reset(),3):this.a(a,b);default:return this.reset(),0}};$.prototype.reset=function(){this.q[this.f]&&this.q[this.f].reset();this.f=0};window.testStartTag=function(){var a=new H("DIV");T("StartTag(div) should match div",2,a.a(G("div1"),1));T("StartTag(div) should not match span",0,a.a(G("span1"),1));T("StartTag(div) should not match /div",0,a.a(G("div1"),-1))};window.testStartTagCase=function(){var a=new H("diV");T("StartTag(diV) should match div",2,a.a(G("div1"),1));T("StartTag(diV) should not match span",0,a.a(G("span1"),1))};
window.testStartTagRegex=function(){var a=new H(/D/);T("StartTag(/D/) should match div",2,a.a(G("div1"),1));T("StartTag(/D/) should not match span",0,a.a(G("span1"),1));T("StartTag(/D/) should not match /div",0,a.a(G("div1"),-1))};window.testStartTagAttributes=function(){var a=new H("DIV",{id:"div1"});T("StartTag(div,id:div1) should match div1",2,a.a(G("div1"),1));T("StartTag(div,id:div2) should not match div1",0,a.a(G("div2"),1))};
window.testStartTagStyle=function(){var a=new H("SPAN",i,{color:"red"});T("StartTag(span,null,color:red) should match span1",2,a.a(G("span1"),1));T("StartTag(span,null,color:blue) should not match span1",0,a.a(G("span2"),1))};window.testStartTagAttributeRegex=function(){var a=new H("SPAN",{id:/span\d/});T("StartTag(span,id:/span\\d/) should match span1",2,a.a(G("span1"),1));T("StartTag(span,id:/span\\d/) should match span2",2,a.a(G("span1"),1))};
window.testEndTag=function(){T("EndTag should match div",2,(new V("DIV")).a(G("div1"),-1))};window.testEndTagRegex=function(){var a=new V(/D/);T("EndTag(/D/) should match /div",2,a.a(G("div1"),-1));T("EndTag(/D/) should not match /span",0,a.a(G("span1"),-1));T("EndTag(/D/) should not match div",0,a.a(G("div1"),1))};
window.testChildMatches=function(){var a=new Y(new H("DIV"),2);T("ChildMatches should match div",1,a.a(G("div1"),1));T("ChildMatches should match /div",1,a.a(G("div1"),-1));T("ChildMatches should match div",1,a.a(G("div2"),1));T("ChildMatches should match /div",1,a.a(G("div2"),-1));T("ChildMatches should finish match at /body",3,a.a(document.body,-1));T("ChildMatches should match div",1,a.a(G("div2"),1));T("ChildMatches should match /div",1,a.a(G("div2"),-1));T("ChildMatches should fail to match at /body: not enough child matches",
0,a.a(document.body,-1))};window.testFullTag=function(){var a=new ya("DIV");T("FullTag(div) should match div",1,a.a(G("div1"),1));T("FullTag(div) should match /div",2,a.a(G("div1"),-1));T("FullTag(div) should start match at div",1,a.a(G("div1"),1));T("FullTag(div) should continue to match span",1,a.a(G("span1"),1));T("FullTag(div) should continue to match /span",1,a.a(G("span1"),-1));T("FullTag(div) should finish match at /div",2,a.a(G("div1"),-1))};
window.testAllChildren=function(){var a=new w;T("AllChildren(div) should match div",1,a.a(G("div1"),1));T("AllChildren(div) should match /div",1,a.a(G("div1"),-1));T("AllChildren(div) should match at /body",3,a.a(document.body,-1));T("AllChildren(div) should start match at div",1,a.a(G("div1"),1));T("AllChildren(div) should continue to match span",1,a.a(G("span1"),1));T("AllChildren(div) should continue to match /span",1,a.a(G("span1"),-1));T("AllChildren(div) should continue to match at /div",1,
a.a(G("div1"),-1));T("AllChildren(div) should finish match at /body",3,a.a(document.body,-1))};window.testText=function(){var a=new X("Text");T("Text should match div3/text()",2,a.a(G("div3").firstChild,0));T("Text should not match div4/text()",0,a.a(G("div4").firstChild,0));T("Text should not match div3",0,a.a(G("div3"),1))};
window.testTextRegex=function(){var a=new X(/Text/);T("Text(regex) should match div3/text()",2,a.a(G("div3").firstChild,0));T("Text(regex) should match div4/text()",2,a.a(G("div4").firstChild,0))};window.testNodeType=function(){var a=new mb(8);T("Comment matcher should match a comment",2,a.a(G("nodeTypes").firstChild,0));T("Comment matcher should not match a text node",0,a.a(G("nodeTypes").lastChild,0))};
window.testSequence=function(){var a=new $([new H("DIV"),new H("SPAN"),new V("SPAN"),new V("DIV")]);T("Sequence[0] should match div1",1,a.a(G("div1"),1));T("Sequence[1] should match span1",1,a.a(G("span1"),1));T("Sequence[2] should match /span1",1,a.a(G("span1"),-1));T("Sequence[3] should match /div1",2,a.a(G("div1"),-1));T("Sequence[0] should match div1 again",1,a.a(G("div1"),1));T("Sequence[1] should match span1 again",1,a.a(G("span1"),1));T("Sequence[2] should match /span1 again",1,a.a(G("span1"),
-1));T("Sequence[3] should match /div1 again",2,a.a(G("div1"),-1));T("Sequence[0] should match div1",1,a.a(G("div1"),1));T("Sequence[1] should not match div1",0,a.a(G("div1"),1));T("Sequence[0] should match div1 after failure",1,a.a(G("div1"),1));T("Sequence[1] should match span1 after failure",1,a.a(G("span1"),1));T("Sequence[2] should match /span1 after failure",1,a.a(G("span1"),-1));T("Sequence[3] should match /div1 after failure",2,a.a(G("div1"),-1))};
window.testRepeat=function(){var a=new Z(new H("B"));T("Repeat[B] should match b1",1,a.a(G("b1"),1));T("Repeat[B] should match b2",1,a.a(G("b2"),1));T("Repeat[B] should backtrack match i1",3,a.a(G("i1"),1));T("Repeat[B] should have match count of 2",2,a.i);T("Repeat[B] should backtrack match i1 even with no b matches",3,a.a(G("i1"),1));T("Repeat[B] should have match count of 0",0,a.i)};
window.testRepeatWithMinimum=function(){var a=new Z(new H("B"),1);T("Repeat[B,1] should match b1",1,a.a(G("b1"),1));T("Repeat[B,1] should match b2",1,a.a(G("b2"),1));T("Repeat[B,1] should backtrack match i1",3,a.a(G("i1"),1));T("Repeat[B,1] should have match count of 2",2,a.i);T("Repeat[B,1] should not match i1",0,a.a(G("i1"),1))};window.testRepeatWithMaximum=function(){T("Repeat[B,1] should match b1",2,(new Z(new H("B"),1,1)).a(G("b1"),1))};
window.testSequenceBacktrack=function(){var a=new $([new Z(new H("SPAN")),new X("X")]),b=G("span3");T('Sequence[Repeat[SPAN],"X"] should match span3',1,a.a(b,1));T('Sequence[Repeat[SPAN],"X"] should match span3.firstChild',1,a.a(b.firstChild,1));T('Sequence[Repeat[SPAN],"X"] should match span3.firstChild.firstChild',1,a.a(b.firstChild.firstChild,1));T('Sequence[Repeat[SPAN],"X"] should finish match text node',2,a.a(b.firstChild.firstChild.firstChild,0))};